dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/link?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 1234

rules:
  - !SHARDING
    tables:
      t_product_order:
        actualDataNodes: ds_0.t_product_order_${0..15}
        tableStrategy:
          standard:
            shardingColumn: user_id
            shardingAlgorithmName: product_order_table_hash_mod
    bindingTables:
      - t_product_order
    shardingAlgorithms:
      product_order_table_hash_mod:
        type: HASH_MOD
        props:
          sharding-count: 16


props:
  sql-show: true
